name: Search and Replace

on:
  push:
    branches:
      - master

jobs:
  search_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Search and Replace
        run: |
          # Add any file extensions you want to search and replace
          file_extensions=".txt .md"

          # Replace the search string and replace string with your desired values
          search_string="lowlighter"
          replace_string="cyberoslab"

          # Find and replace in each file
          find_replace() {
            file="$1"
            echo "Processing file: $file"
            sed -i "s/lowlighter/cyberoslab/g" "+"
          }

          # Find and replace in specified file extensions
          for extension in $file_extensions; do
            find . -name "*$extension" -type f | while read -r file; do
              find_replace "$file"
            done
          done

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Perform search and replace using GitHub Actions"
          git push
