name: Search and Replace

on:
  push:
    branches-ignore:
      - master

jobs:
  search_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch All Branches
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all

      - name: Search and Replace
        run: |
          # Replace the search string and replace string with your desired values
          search_string="lowlighter"
          replace_string="cyberoslab"

          # Find and replace in each file
          find_replace() {
            file="$1"
            echo "Processing file: $file"
            sed -i "s/$search_string/$replace_string/g" "$file"
          }

          # Find and replace in all branches
          branches=$(git branch -r | grep -v '\->' | sed -E 's/origin\///')
          for branch in $branches; do
            git checkout -f "$branch"
            find . -type f ! -path "./.git/*" -exec bash -c 'find_replace "$0"' {} \;
          done

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Perform search and replace using GitHub Actions"
          git push
